### ISSUE TITLE
Futuro bardo

### ISSUE THREAD

**Issue by MattSchaab** [TeoKohan/LudumDare39#1] opened 2017-07-28 01:41 UTC
Hubo quilombo

**Comment by pyritewolf** [comment] 2017-07-28 01:41
Para resolverlo, desenquilombate
besi

**Comment by MattSchaab** [comment] 2017-07-28 01:42
> hu3

> hu3hu3

**Comment by MattSchaab** [comment] 2017-07-28 01:42
NOOOo

**Comment by TK-firewill** [comment] 2017-07-28 01:43
Marking this as closed as the issue is non euclidean.

**Closed as completed** 2017-07-28 01:46 UTC
Labels: help wanted
